### PR TITLE
added flattened H5MD docs

### PR DESCRIPTION
**Pull request by JFRudzinski**
Added my H5MD docs, but I flattened the structure a bit. I guess there are still technically 4 levels, since I kept the H5MD-specific references, but I think it is still manageable this way.

Let me know what you think!

### CODE REVIEW

**Comment by ndaelman-hu** [comment]
Do you want feedback on the integration or also the specific text?

**Comment by JFRudzinski** [comment]
> Do you want feedback on the integration or also the specific text?

Good point. I am happy to receive feedback on the text, but both of these PR's are in a preliminary stage, so I think it's not worth your time to go through at this point. Especially this one. For the parser plugin one, you could also give feedback on the "text", at least in terms of the general organization, section titles, basic content, etc., so that I can make adjustments moving forward.

**Review by JosePizarro3 — APPROVED** [review]
If this is an initial flattened merge, go ahead. Later we can review the content as you will work on it.

**Comment by ndaelman-hu** [comment]
> Good point. I am happy to receive feedback on the text, but both of these PR's are in a preliminary stage, so I think it's not worth your time to go through at this point.

Too late for the other one, already completed it.

**Pull request merged**
