### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by ndaelman-hu**
Fix the missing image paths under `Upload and Publish`.

### CODE REVIEW

**Comment by JosePizarro3** [comment]
Nice, do you mind fixing the img src in each of the md documents in uploading_and_publishing/?

**Comment by ndaelman-hu** [comment]
> Nice, do you mind fixing the img src in each of the md documents in uploading_and_publishing/?

Can do that, but they should already be rendering, right?
It seems that mkdocs fixes the root once `overview.md` is fine.

**Comment by JosePizarro3** [comment]
Really? Ok, let's see. We merge, and if the links are still broken, I will fix it directly to the main.

**Review by JosePizarro3 — APPROVED** [review]

**Comment by ndaelman-hu** [comment]
You can check locally too, but 

> Really? Ok, let's see. We merge, and if the links are still broken, I will fix it directly to the main.

You can check it locally, but for me it works at least.
If it doesn't, we just re-open the issue.

**Comment by JosePizarro3** [comment]
It seems it didn't fix it, at least now I can see the image in the overview page, but not in the others.

Problem is that locally when doing `mkdocs serve` is doing something different as when deploying in the gh-pages, but I didn't find any information about this. Don't worry, I will push the new path to the main directly, no need to reopen this.

**Pull request merged**
